### PR TITLE
WIP: Modernize Trie code

### PR DESCRIPTION
**Pull request by quinnj**
Dealing with Tries/Suffix Trees in one of my classes, so I thought I'd take a look at this code. Apart from updating some deprecated methods, I'm taking a stab at making this more "Base-like", by using `push!` instead of `assign`, taking away the `default` in `get`, etc.

Also added a `Trie` constructor that takes a vector of Strings, which is convenient.

One change I made was taking out the type parameter for the `Trie` and having everything the Dict default to `(String=>Trie)`. I think the only other valid key you would want to use is an Int if you made the keys indices rather than characters, but I'm also digging into the real uses of Tries, so I may be wrong here. Would you really want to use something other than Int/String/Char as a key?

The main reason I wanted to default to String is to add `compress()` and `decompress()` to be able to merge single path keys together. 

Anyway, I'd appreciate any other input or ideas on improving or making this otherwise more useful.

### CODE REVIEW

**Comment by quinnj** [comment]
My other question is what the purpose of the `prefix` argument in the `keys` method is for (it prepends the prefix to every key in the Trie). Not trying to say we shouldn't have it, I just don't know how that would be useful.

**Comment by kmsquire** [comment]
Hi Jacob, Can't look at this closely right now, but you might look at #1 and consider updating the patch to DataStructures.jl instead.  I think someone just needs to pull the trigger there.  Cheers!

**Comment by quinnj** [comment]
Yeah, I was thinking of working on stuff here before it was merged over, but I'll move the PR to DataStructures.

**Comment by aviks** [comment]
This was moved to DataStructures, I think. https://github.com/JuliaLang/DataStructures.jl/pull/20

**Comment by quinnj** [comment]
Indeed. Thanks for closing.

**Pull request closed without merging**
